#!/bin/bash

#
# MIT License
#
# Copyright (c) 2018 librarianrabbit
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#

# WARNING: XMP does not support binary files directly.
# Use base64 encoded files if possible.
#
# WARNING: Most websites and tools might remove the entire XMP metadata or the unknown/custom tags.
# Keep backups of *everything*.

function show_usage () {
	echo ""
	echo "Usage: xmp-remove \"image.jpg\""
	echo ""
	echo "This tool removes all XMP metadata from the input file."
	echo "WARNING: All previous XMP metadata is is permanently deleted. Please backup all related files."
	echo ""
	echo "Dependencies: exiftool"
	echo ""
}

# Tools and paths
EXIFTOOL="exiftool"

if [ "$#" -lt "1" ];
then
	echo "ERROR: Image filename not provided."
	show_usage
	exit 1
fi

# File: First parameter.
FILE="$1"

if [ ! -f "$FILE" ]; then
	echo "ERROR: The image filename provided does not exists."
	exit 1
fi

CMD="-xmp:xmp="

# Calls exiftool with the parameters to remove all XMP metadata existing in the input file.
"$EXIFTOOL" "$CMD" "$FILE"
